#[Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)
#
#This project is licensed under the Apache-2.0 license - see the LICENSE file for details.
#
#Copyright (c) 2024-present, Zhai JinPei

minio:
  endpoint: http://10.20.245.160:9000
  accesskey: minioadmin
  secretkey: minioadmin

spring:
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 7000
